pipeline {
  agent any

  tools {
    jdk 'jdk-17'
    maven 'Maven 3.6.3'
  }

  environment {
    SONAR_TOKEN = credentials('sonar-token')
  }

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/efrei-aicylaa/mon-projet-springboot.git'
      }
    }

    stage('Build') {
      steps {
        dir('monprojet') {
          sh 'mvn clean install'
        }
      }
    }

    stage('Analyse SonarQube') {
      steps {
        withSonarQubeEnv('SonarQube') {
          dir('monprojet') {
            sh 'mvn verify sonar:sonar -Dsonar.projectKey=AppSpringboot -Dsonar.login=$SONAR_TOKEN'
          }
        }
      }
    }
  }
}
